### ISSUE TITLE
Trigger failure

### ISSUE THREAD

**Issue by gtaylor** [Graylog2/graylog2-alarmcallback-hipchat#5]
Getting this exception when the handler is triggered:

```
2015-07-01T21:42:35.933Z WARN  [DefaultChannelPipeline] An exception was thrown by a user handler while handling an exception event ([id: 0x2c6faccd, /169.254.169.254:57783 :> /104.197.15.116:12900] EXCEPTION: java.io.IOException: Connection reset by peer)
java.lang.NullPointerException
        at org.graylog2.jersey.container.netty.NettyContainer.exceptionCaught(NettyContainer.java:412)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:112)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
        at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:622)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Running the packaged Wheezy graylog-server 1.1.4-1.

**Comment by gtaylor** [comment]
It looks like this was from me using a v1 API token instead of the new-style room tokens. Might be worth exaggerating that distinction in the documentation so people don't do what I did!
